// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: depth.proto

package depth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DepthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Depth         float64                `protobuf:"fixed64,1,opt,name=depth,proto3" json:"depth,omitempty"`
	Pressure      float64                `protobuf:"fixed64,2,opt,name=pressure,proto3" json:"pressure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepthRequest) Reset() {
	*x = DepthRequest{}
	mi := &file_depth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepthRequest) ProtoMessage() {}

func (x *DepthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_depth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepthRequest.ProtoReflect.Descriptor instead.
func (*DepthRequest) Descriptor() ([]byte, []int) {
	return file_depth_proto_rawDescGZIP(), []int{0}
}

func (x *DepthRequest) GetDepth() float64 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *DepthRequest) GetPressure() float64 {
	if x != nil {
		return x.Pressure
	}
	return 0
}

type DepthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepthResponse) Reset() {
	*x = DepthResponse{}
	mi := &file_depth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepthResponse) ProtoMessage() {}

func (x *DepthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_depth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepthResponse.ProtoReflect.Descriptor instead.
func (*DepthResponse) Descriptor() ([]byte, []int) {
	return file_depth_proto_rawDescGZIP(), []int{1}
}

func (x *DepthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_depth_proto protoreflect.FileDescriptor

const file_depth_proto_rawDesc = "" +
	"\n" +
	"\vdepth.proto\x12\x05depth\"@\n" +
	"\fDepthRequest\x12\x14\n" +
	"\x05depth\x18\x01 \x01(\x01R\x05depth\x12\x1a\n" +
	"\bpressure\x18\x02 \x01(\x01R\bpressure\"'\n" +
	"\rDepthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2E\n" +
	"\fDepthService\x125\n" +
	"\bSetDepth\x12\x13.depth.DepthRequest\x1a\x14.depth.DepthResponseB\x19Z\x17zpicier/src/GO/pb;depthb\x06proto3"

var (
	file_depth_proto_rawDescOnce sync.Once
	file_depth_proto_rawDescData []byte
)

func file_depth_proto_rawDescGZIP() []byte {
	file_depth_proto_rawDescOnce.Do(func() {
		file_depth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_depth_proto_rawDesc), len(file_depth_proto_rawDesc)))
	})
	return file_depth_proto_rawDescData
}

var file_depth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_depth_proto_goTypes = []any{
	(*DepthRequest)(nil),  // 0: depth.DepthRequest
	(*DepthResponse)(nil), // 1: depth.DepthResponse
}
var file_depth_proto_depIdxs = []int32{
	0, // 0: depth.DepthService.SetDepth:input_type -> depth.DepthRequest
	1, // 1: depth.DepthService.SetDepth:output_type -> depth.DepthResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_depth_proto_init() }
func file_depth_proto_init() {
	if File_depth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_depth_proto_rawDesc), len(file_depth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_depth_proto_goTypes,
		DependencyIndexes: file_depth_proto_depIdxs,
		MessageInfos:      file_depth_proto_msgTypes,
	}.Build()
	File_depth_proto = out.File
	file_depth_proto_goTypes = nil
	file_depth_proto_depIdxs = nil
}
