// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: depth.proto

package depth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DepthService_SetDepth_FullMethodName = "/depth.DepthService/SetDepth"
)

// DepthServiceClient is the client API for DepthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DepthServiceClient interface {
	SetDepth(ctx context.Context, in *DepthRequest, opts ...grpc.CallOption) (*DepthResponse, error)
}

type depthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDepthServiceClient(cc grpc.ClientConnInterface) DepthServiceClient {
	return &depthServiceClient{cc}
}

func (c *depthServiceClient) SetDepth(ctx context.Context, in *DepthRequest, opts ...grpc.CallOption) (*DepthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DepthResponse)
	err := c.cc.Invoke(ctx, DepthService_SetDepth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DepthServiceServer is the server API for DepthService service.
// All implementations must embed UnimplementedDepthServiceServer
// for forward compatibility.
type DepthServiceServer interface {
	SetDepth(context.Context, *DepthRequest) (*DepthResponse, error)
	mustEmbedUnimplementedDepthServiceServer()
}

// UnimplementedDepthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDepthServiceServer struct{}

func (UnimplementedDepthServiceServer) SetDepth(context.Context, *DepthRequest) (*DepthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDepth not implemented")
}
func (UnimplementedDepthServiceServer) mustEmbedUnimplementedDepthServiceServer() {}
func (UnimplementedDepthServiceServer) testEmbeddedByValue()                      {}

// UnsafeDepthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DepthServiceServer will
// result in compilation errors.
type UnsafeDepthServiceServer interface {
	mustEmbedUnimplementedDepthServiceServer()
}

func RegisterDepthServiceServer(s grpc.ServiceRegistrar, srv DepthServiceServer) {
	// If the following call pancis, it indicates UnimplementedDepthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DepthService_ServiceDesc, srv)
}

func _DepthService_SetDepth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepthServiceServer).SetDepth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DepthService_SetDepth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepthServiceServer).SetDepth(ctx, req.(*DepthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DepthService_ServiceDesc is the grpc.ServiceDesc for DepthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DepthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "depth.DepthService",
	HandlerType: (*DepthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetDepth",
			Handler:    _DepthService_SetDepth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "depth.proto",
}
