// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: pwm.proto

package pwm

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PWMService_GetPWM_FullMethodName = "/pwm.PWMService/GetPWM"
)

// PWMServiceClient is the client API for PWMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PWMServiceClient interface {
	GetPWM(ctx context.Context, in *GetPWMRequest, opts ...grpc.CallOption) (*PWMValues, error)
}

type pWMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPWMServiceClient(cc grpc.ClientConnInterface) PWMServiceClient {
	return &pWMServiceClient{cc}
}

func (c *pWMServiceClient) GetPWM(ctx context.Context, in *GetPWMRequest, opts ...grpc.CallOption) (*PWMValues, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PWMValues)
	err := c.cc.Invoke(ctx, PWMService_GetPWM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PWMServiceServer is the server API for PWMService service.
// All implementations must embed UnimplementedPWMServiceServer
// for forward compatibility.
type PWMServiceServer interface {
	GetPWM(context.Context, *GetPWMRequest) (*PWMValues, error)
	mustEmbedUnimplementedPWMServiceServer()
}

// UnimplementedPWMServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPWMServiceServer struct{}

func (UnimplementedPWMServiceServer) GetPWM(context.Context, *GetPWMRequest) (*PWMValues, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPWM not implemented")
}
func (UnimplementedPWMServiceServer) mustEmbedUnimplementedPWMServiceServer() {}
func (UnimplementedPWMServiceServer) testEmbeddedByValue()                    {}

// UnsafePWMServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PWMServiceServer will
// result in compilation errors.
type UnsafePWMServiceServer interface {
	mustEmbedUnimplementedPWMServiceServer()
}

func RegisterPWMServiceServer(s grpc.ServiceRegistrar, srv PWMServiceServer) {
	// If the following call pancis, it indicates UnimplementedPWMServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PWMService_ServiceDesc, srv)
}

func _PWMService_GetPWM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPWMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PWMServiceServer).GetPWM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PWMService_GetPWM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PWMServiceServer).GetPWM(ctx, req.(*GetPWMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PWMService_ServiceDesc is the grpc.ServiceDesc for PWMService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PWMService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pwm.PWMService",
	HandlerType: (*PWMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPWM",
			Handler:    _PWMService_GetPWM_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pwm.proto",
}
