// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: pwm.proto

package pwm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PWMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     int32                  `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Speed         int32                  `protobuf:"varint,2,opt,name=speed,proto3" json:"speed,omitempty"` // microseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PWMRequest) Reset() {
	*x = PWMRequest{}
	mi := &file_pwm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PWMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PWMRequest) ProtoMessage() {}

func (x *PWMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pwm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PWMRequest.ProtoReflect.Descriptor instead.
func (*PWMRequest) Descriptor() ([]byte, []int) {
	return file_pwm_proto_rawDescGZIP(), []int{0}
}

func (x *PWMRequest) GetChannelId() int32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *PWMRequest) GetSpeed() int32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type PWMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PWMResponse) Reset() {
	*x = PWMResponse{}
	mi := &file_pwm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PWMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PWMResponse) ProtoMessage() {}

func (x *PWMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pwm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PWMResponse.ProtoReflect.Descriptor instead.
func (*PWMResponse) Descriptor() ([]byte, []int) {
	return file_pwm_proto_rawDescGZIP(), []int{1}
}

func (x *PWMResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_pwm_proto protoreflect.FileDescriptor

const file_pwm_proto_rawDesc = "" +
	"\n" +
	"\tpwm.proto\x12\x03pwm\"A\n" +
	"\n" +
	"PWMRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\x05R\tchannelId\x12\x14\n" +
	"\x05speed\x18\x02 \x01(\x05R\x05speed\"%\n" +
	"\vPWMResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status29\n" +
	"\n" +
	"PWMService\x12+\n" +
	"\x06SetPWM\x12\x0f.pwm.PWMRequest\x1a\x10.pwm.PWMResponseB\x17Z\x15zpicier/src/GO/pb;pwmb\x06proto3"

var (
	file_pwm_proto_rawDescOnce sync.Once
	file_pwm_proto_rawDescData []byte
)

func file_pwm_proto_rawDescGZIP() []byte {
	file_pwm_proto_rawDescOnce.Do(func() {
		file_pwm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pwm_proto_rawDesc), len(file_pwm_proto_rawDesc)))
	})
	return file_pwm_proto_rawDescData
}

var file_pwm_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pwm_proto_goTypes = []any{
	(*PWMRequest)(nil),  // 0: pwm.PWMRequest
	(*PWMResponse)(nil), // 1: pwm.PWMResponse
}
var file_pwm_proto_depIdxs = []int32{
	0, // 0: pwm.PWMService.SetPWM:input_type -> pwm.PWMRequest
	1, // 1: pwm.PWMService.SetPWM:output_type -> pwm.PWMResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pwm_proto_init() }
func file_pwm_proto_init() {
	if File_pwm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pwm_proto_rawDesc), len(file_pwm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pwm_proto_goTypes,
		DependencyIndexes: file_pwm_proto_depIdxs,
		MessageInfos:      file_pwm_proto_msgTypes,
	}.Build()
	File_pwm_proto = out.File
	file_pwm_proto_goTypes = nil
	file_pwm_proto_depIdxs = nil
}
