// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: joy.proto

package joystick

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JoystickService_UpdateState_FullMethodName = "/joystick.JoystickService/UpdateState"
)

// JoystickServiceClient is the client API for JoystickService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JoystickServiceClient interface {
	UpdateState(ctx context.Context, in *JoystickRequest, opts ...grpc.CallOption) (*JoystickResponse, error)
}

type joystickServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJoystickServiceClient(cc grpc.ClientConnInterface) JoystickServiceClient {
	return &joystickServiceClient{cc}
}

func (c *joystickServiceClient) UpdateState(ctx context.Context, in *JoystickRequest, opts ...grpc.CallOption) (*JoystickResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoystickResponse)
	err := c.cc.Invoke(ctx, JoystickService_UpdateState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JoystickServiceServer is the server API for JoystickService service.
// All implementations must embed UnimplementedJoystickServiceServer
// for forward compatibility.
type JoystickServiceServer interface {
	UpdateState(context.Context, *JoystickRequest) (*JoystickResponse, error)
	mustEmbedUnimplementedJoystickServiceServer()
}

// UnimplementedJoystickServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJoystickServiceServer struct{}

func (UnimplementedJoystickServiceServer) UpdateState(context.Context, *JoystickRequest) (*JoystickResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateState not implemented")
}
func (UnimplementedJoystickServiceServer) mustEmbedUnimplementedJoystickServiceServer() {}
func (UnimplementedJoystickServiceServer) testEmbeddedByValue()                         {}

// UnsafeJoystickServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JoystickServiceServer will
// result in compilation errors.
type UnsafeJoystickServiceServer interface {
	mustEmbedUnimplementedJoystickServiceServer()
}

func RegisterJoystickServiceServer(s grpc.ServiceRegistrar, srv JoystickServiceServer) {
	// If the following call pancis, it indicates UnimplementedJoystickServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JoystickService_ServiceDesc, srv)
}

func _JoystickService_UpdateState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoystickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JoystickServiceServer).UpdateState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JoystickService_UpdateState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JoystickServiceServer).UpdateState(ctx, req.(*JoystickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JoystickService_ServiceDesc is the grpc.ServiceDesc for JoystickService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JoystickService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "joystick.JoystickService",
	HandlerType: (*JoystickServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateState",
			Handler:    _JoystickService_UpdateState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "joy.proto",
}
