// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: imu.proto

package imu

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IMURequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pitch         float64                `protobuf:"fixed64,1,opt,name=pitch,proto3" json:"pitch,omitempty"`
	Roll          float64                `protobuf:"fixed64,2,opt,name=roll,proto3" json:"roll,omitempty"`
	Yaw           float64                `protobuf:"fixed64,3,opt,name=yaw,proto3" json:"yaw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IMURequest) Reset() {
	*x = IMURequest{}
	mi := &file_imu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IMURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMURequest) ProtoMessage() {}

func (x *IMURequest) ProtoReflect() protoreflect.Message {
	mi := &file_imu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMURequest.ProtoReflect.Descriptor instead.
func (*IMURequest) Descriptor() ([]byte, []int) {
	return file_imu_proto_rawDescGZIP(), []int{0}
}

func (x *IMURequest) GetPitch() float64 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

func (x *IMURequest) GetRoll() float64 {
	if x != nil {
		return x.Roll
	}
	return 0
}

func (x *IMURequest) GetYaw() float64 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

type IMUResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IMUResponse) Reset() {
	*x = IMUResponse{}
	mi := &file_imu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IMUResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMUResponse) ProtoMessage() {}

func (x *IMUResponse) ProtoReflect() protoreflect.Message {
	mi := &file_imu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMUResponse.ProtoReflect.Descriptor instead.
func (*IMUResponse) Descriptor() ([]byte, []int) {
	return file_imu_proto_rawDescGZIP(), []int{1}
}

func (x *IMUResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_imu_proto protoreflect.FileDescriptor

const file_imu_proto_rawDesc = "" +
	"\n" +
	"\timu.proto\x12\x03imu\"H\n" +
	"\n" +
	"IMURequest\x12\x14\n" +
	"\x05pitch\x18\x01 \x01(\x01R\x05pitch\x12\x12\n" +
	"\x04roll\x18\x02 \x01(\x01R\x04roll\x12\x10\n" +
	"\x03yaw\x18\x03 \x01(\x01R\x03yaw\"%\n" +
	"\vIMUResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2A\n" +
	"\n" +
	"IMUService\x123\n" +
	"\x0eSetEulerAngles\x12\x0f.imu.IMURequest\x1a\x10.imu.IMUResponseB\x17Z\x15zpicier/src/GO/pb;imub\x06proto3"

var (
	file_imu_proto_rawDescOnce sync.Once
	file_imu_proto_rawDescData []byte
)

func file_imu_proto_rawDescGZIP() []byte {
	file_imu_proto_rawDescOnce.Do(func() {
		file_imu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_imu_proto_rawDesc), len(file_imu_proto_rawDesc)))
	})
	return file_imu_proto_rawDescData
}

var file_imu_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_imu_proto_goTypes = []any{
	(*IMURequest)(nil),  // 0: imu.IMURequest
	(*IMUResponse)(nil), // 1: imu.IMUResponse
}
var file_imu_proto_depIdxs = []int32{
	0, // 0: imu.IMUService.SetEulerAngles:input_type -> imu.IMURequest
	1, // 1: imu.IMUService.SetEulerAngles:output_type -> imu.IMUResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_imu_proto_init() }
func file_imu_proto_init() {
	if File_imu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_imu_proto_rawDesc), len(file_imu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_imu_proto_goTypes,
		DependencyIndexes: file_imu_proto_depIdxs,
		MessageInfos:      file_imu_proto_msgTypes,
	}.Build()
	File_imu_proto = out.File
	file_imu_proto_goTypes = nil
	file_imu_proto_depIdxs = nil
}
