// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: imu.proto

package imu

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IMUService_SetEulerAngles_FullMethodName = "/imu.IMUService/SetEulerAngles"
)

// IMUServiceClient is the client API for IMUService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IMUServiceClient interface {
	SetEulerAngles(ctx context.Context, in *IMURequest, opts ...grpc.CallOption) (*IMUResponse, error)
}

type iMUServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIMUServiceClient(cc grpc.ClientConnInterface) IMUServiceClient {
	return &iMUServiceClient{cc}
}

func (c *iMUServiceClient) SetEulerAngles(ctx context.Context, in *IMURequest, opts ...grpc.CallOption) (*IMUResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IMUResponse)
	err := c.cc.Invoke(ctx, IMUService_SetEulerAngles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IMUServiceServer is the server API for IMUService service.
// All implementations must embed UnimplementedIMUServiceServer
// for forward compatibility.
type IMUServiceServer interface {
	SetEulerAngles(context.Context, *IMURequest) (*IMUResponse, error)
	mustEmbedUnimplementedIMUServiceServer()
}

// UnimplementedIMUServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIMUServiceServer struct{}

func (UnimplementedIMUServiceServer) SetEulerAngles(context.Context, *IMURequest) (*IMUResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetEulerAngles not implemented")
}
func (UnimplementedIMUServiceServer) mustEmbedUnimplementedIMUServiceServer() {}
func (UnimplementedIMUServiceServer) testEmbeddedByValue()                    {}

// UnsafeIMUServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IMUServiceServer will
// result in compilation errors.
type UnsafeIMUServiceServer interface {
	mustEmbedUnimplementedIMUServiceServer()
}

func RegisterIMUServiceServer(s grpc.ServiceRegistrar, srv IMUServiceServer) {
	// If the following call pancis, it indicates UnimplementedIMUServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IMUService_ServiceDesc, srv)
}

func _IMUService_SetEulerAngles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IMURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMUServiceServer).SetEulerAngles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IMUService_SetEulerAngles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMUServiceServer).SetEulerAngles(ctx, req.(*IMURequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IMUService_ServiceDesc is the grpc.ServiceDesc for IMUService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IMUService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "imu.IMUService",
	HandlerType: (*IMUServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetEulerAngles",
			Handler:    _IMUService_SetEulerAngles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "imu.proto",
}
