# horizontal_gripper_camera:
#   index: /dev/logitech_camera_1
#   width: 352
#   height: 480
#   format: MJPG
#   type: NORMAL
#   fps: 15
#   port: 8081
vertical_gripper_camera:
  index: right_view.mp4
  width: 352
  height: 480
  format: MJPG
  type: NORMAL
  fps: 15
  port: 8082
# photosphere:
#   index: /dev/fisheye_camera
#   width: 640
#   height: 480
#   format: MJPG
#   type: NORMAL
#   fps: 15
#   port: 8083
# rapoo_camera:
#   index: /dev/rapoo_camera
#   width: 352
#   height: 288
#   format: MJPG
#   type: NORMAL
#   fps: 15
#   port: 8084
# stereo_camera:
#   index: /dev/stereo_camera
#   focal_length: 3 #mm
#   baseline: 12 #cm
#   width: 640
#   height: 480
#   format: MJPG
#   type: NORMAL
#   port: 8085
#   fps: 30
# left_stereo:
#   index: /dev/stereo_left #--> video17
#   width: 640
#   height: 480
#   format: MJPG
#   type: NORMAL
#   fps: 15
#   port: 8085
# right_stereo:
#   index: /dev/stereo_right  #--> video18
#   width: 640
#   height: 480
#   format: MJPG
#   type: NORMAL
#   fps: 15
#   port: 8086


  # left_stereo:  
  #   index: /dev/stereo_left #--> video17
  #   width: 640
  #   height: 480
  #   format: MJPG
  #   type: NORMAL
  #   fps: 30
  #   port: 8086
  # right_stereo:
  #   index: /dev/stereo_right  #--> video18
  #   width: 640
  #   height: 480
  #   format: MJPG
  #   type: NORMAL
  #   fps: 30
  #   port: 8087
  # stitched:
  #   index: /dev/stereo_stitched #--> video19
  #   width: 1280
  #   height: 480
  #   format: MJPG
  #   type: STITCHED
  #   fps: 30
  #   port: 8088




# # #Rapoo and left cameras probably doesnt not suppoer mjpg format