#LEFTSIDE
button_l1: RESET_HEAVE #SWITCHING
button_l2: LEFTGRIPPER  #SWITCHING
button_left: LEFTGRIPPER_UP_DOWN
button_right: LEFTGRIPPER_UP_OPEN #NOT WORKING
button_share: PHOTOSPHERE_SERVO_LEFT
button_options: PHOTOSPHERE_SERVO_RIGHT
button_pad: RESET

#RIGHTSIDE
button_r1: VERTICALGRIPPER_LEFT_RIGHT
button_x: VERTICALGRIPPER

#FRONTSIDE
button_r2: FRONTGRIPPER #SWITCHING
button_bot: STEREO_SERVO_DOWN
button_top: STEREO_SERVO_UP
button_o:  DCFRONTGRIPPER_RIGHT
button_rect: DCFRONTGRIPPER_LEFT 

#BACKSIDE
button_tri: SYRINGE #SWITCHING

#MISC
button_l3: HEAVE_DOWN
button_r3: HEAVE_UP