# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: imu.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'imu.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\timu.proto\x12\x03imu\"6\n\nIMURequest\x12\r\n\x05pitch\x18\x01 \x01(\x01\x12\x0c\n\x04roll\x18\x02 \x01(\x01\x12\x0b\n\x03yaw\x18\x03 \x01(\x01\"\x1d\n\x0bIMUResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2A\n\nIMUService\x12\x33\n\x0eSetEulerAngles\x12\x0f.imu.IMURequest\x1a\x10.imu.IMUResponseB\x17Z\x15zpicier/src/GO/pb;imub\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'imu_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\025zpicier/src/GO/pb;imu'
  _globals['_IMUREQUEST']._serialized_start=18
  _globals['_IMUREQUEST']._serialized_end=72
  _globals['_IMURESPONSE']._serialized_start=74
  _globals['_IMURESPONSE']._serialized_end=103
  _globals['_IMUSERVICE']._serialized_start=105
  _globals['_IMUSERVICE']._serialized_end=170
# @@protoc_insertion_point(module_scope)
