# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: joy.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'joy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tjoy.proto\x12\x08joystick\"\xd4\x01\n\x0fJoystickRequest\x12\x37\n\x07\x62uttons\x18\x01 \x03(\x0b\x32&.joystick.JoystickRequest.ButtonsEntry\x12\x0e\n\x06\x61xis_x\x18\x02 \x01(\x01\x12\x0e\n\x06\x61xis_y\x18\x03 \x01(\x01\x12\x0e\n\x06\x61xis_z\x18\x04 \x01(\x01\x12\x0c\n\x04roll\x18\x05 \x01(\x01\x12\r\n\x05pitch\x18\x06 \x01(\x01\x12\x0b\n\x03yaw\x18\x07 \x01(\x01\x1a.\n\x0c\x42uttonsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01\"\"\n\x10JoystickResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2W\n\x0fJoystickService\x12\x44\n\x0bUpdateState\x12\x19.joystick.JoystickRequest\x1a\x1a.joystick.JoystickResponseB%Z#zpicier/src/GO/pb/joystick;joystickb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'joy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#zpicier/src/GO/pb/joystick;joystick'
  _globals['_JOYSTICKREQUEST_BUTTONSENTRY']._loaded_options = None
  _globals['_JOYSTICKREQUEST_BUTTONSENTRY']._serialized_options = b'8\001'
  _globals['_JOYSTICKREQUEST']._serialized_start=24
  _globals['_JOYSTICKREQUEST']._serialized_end=236
  _globals['_JOYSTICKREQUEST_BUTTONSENTRY']._serialized_start=190
  _globals['_JOYSTICKREQUEST_BUTTONSENTRY']._serialized_end=236
  _globals['_JOYSTICKRESPONSE']._serialized_start=238
  _globals['_JOYSTICKRESPONSE']._serialized_end=272
  _globals['_JOYSTICKSERVICE']._serialized_start=274
  _globals['_JOYSTICKSERVICE']._serialized_end=361
# @@protoc_insertion_point(module_scope)
