# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import pwm_pb2 as pwm__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pwm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PWMServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetPWM = channel.unary_unary(
                '/pwm.PWMService/SetPWM',
                request_serializer=pwm__pb2.PWMRequest.SerializeToString,
                response_deserializer=pwm__pb2.PWMResponse.FromString,
                _registered_method=True)


class PWMServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetPWM(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PWMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetPWM': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPWM,
                    request_deserializer=pwm__pb2.PWMRequest.FromString,
                    response_serializer=pwm__pb2.PWMResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pwm.PWMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pwm.PWMService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PWMService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetPWM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pwm.PWMService/SetPWM',
            pwm__pb2.PWMRequest.SerializeToString,
            pwm__pb2.PWMResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
