# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pwm.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'pwm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tpwm.proto\x12\x03pwm\"/\n\nPWMRequest\x12\x12\n\nchannel_id\x18\x01 \x01(\x05\x12\r\n\x05speed\x18\x02 \x01(\x05\"\x1d\n\x0bPWMResponse\x12\x0e\n\x06status\x18\x01 \x01(\t29\n\nPWMService\x12+\n\x06SetPWM\x12\x0f.pwm.PWMRequest\x1a\x10.pwm.PWMResponseB\x17Z\x15zpicier/src/GO/pb;pwmb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pwm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\025zpicier/src/GO/pb;pwm'
  _globals['_PWMREQUEST']._serialized_start=18
  _globals['_PWMREQUEST']._serialized_end=65
  _globals['_PWMRESPONSE']._serialized_start=67
  _globals['_PWMRESPONSE']._serialized_end=96
  _globals['_PWMSERVICE']._serialized_start=98
  _globals['_PWMSERVICE']._serialized_end=155
# @@protoc_insertion_point(module_scope)
