# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pwm.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'pwm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tpwm.proto\x12\x03pwm\"\x0f\n\rGetPWMRequest\"1\n\x08PWMEntry\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\x05\x12\x14\n\x0cmicroseconds\x18\x02 \x01(\x01\"*\n\tPWMValues\x12\x1d\n\x06values\x18\x01 \x03(\x0b\x32\r.pwm.PWMEntry2:\n\nPWMService\x12,\n\x06GetPWM\x12\x12.pwm.GetPWMRequest\x1a\x0e.pwm.PWMValuesB\x17Z\x15zpicier/src/GO/pb;pwmb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pwm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\025zpicier/src/GO/pb;pwm'
  _globals['_GETPWMREQUEST']._serialized_start=18
  _globals['_GETPWMREQUEST']._serialized_end=33
  _globals['_PWMENTRY']._serialized_start=35
  _globals['_PWMENTRY']._serialized_end=84
  _globals['_PWMVALUES']._serialized_start=86
  _globals['_PWMVALUES']._serialized_end=128
  _globals['_PWMSERVICE']._serialized_start=130
  _globals['_PWMSERVICE']._serialized_end=188
# @@protoc_insertion_point(module_scope)
